import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Footer from '~/components/layouts/footer';
import './globals.css';
import Header from '~/components/layouts/header';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <main style={{ minHeight: 'calc(100vh - 140px)' }}>{children}</main>
        <Footer />

        {/* Global Animated Background */}
        <div className="animatedBackground">
          <div className="floatingElement" style={{ top: '10%', left: '10%' }}>
            💻
          </div>
          <div className="floatingElement" style={{ top: '20%', right: '15%' }}>
            🚀
          </div>
          <div
            className="floatingElement"
            style={{ bottom: '30%', left: '20%' }}
          >
            ⚡
          </div>
          <div
            className="floatingElement"
            style={{ bottom: '20%', right: '10%' }}
          >
            🎯
          </div>
          <div className="floatingElement" style={{ top: '60%', left: '5%' }}>
            ⭐
          </div>
          <div className="floatingElement" style={{ top: '70%', right: '5%' }}>
            🎨
          </div>
        </div>
      </body>
    </html>
  );
}
